<?php

namespace Manager\Controller;

/**
 * @author zhouwei
 * Class OrderController
 * @package Merchant\Controller
 * 订单管理 - 订单列表 - 控制器
 */
class OrderController extends BaseController {

    public function getIndexRelation()
    {
        parent::getIndexRelation(); // TODO: Change the autogenerated stub
    }

    /**
     * 频道列表页
     */
    function index() {
        $this->checkRule(self::$rule);
        $Object = D(CONTROLLER_NAME,'Logic');
        $result = $Object->getList(I('request.'));
        if($result) {
            $this->assign('page', $result['page']);
            $this->assign('list', $result['list']);
            $this->assign('deliverOrder', $result['deliverOrder']);
            $this->assign('awaitOrder', $result['awaitOrder']);
        } else {
            $this->error($Object->getLogicError());
        }
        // 记录当前列表页的cookie
        Cookie('__forward__',$_SERVER['REQUEST_URI']);
        $this->getIndexRelation();
        $this->display('index');
    }
}
