<?php

namespace Merchant\Controller;

/**
 * [广告办理]
 * @author zhouwei
 * Class AdPositionController
 * @package Merchant\Controller
 */
class AdPositionController extends BaseController {

    /**
     * 判断数量
     */
    public function judgeAmount()
    {
        $post = $_POST;
        $model = M('AdPosition')->where(array('region'=>$post['region'],'type' => $post['type'],'location'=>$post['location'],'start_time'=>strtotime($post['today']),))->count();
        if($model > 0){
            $this->ajaxReturn(array('status'=>0,'info'=>'所选择的日期已被其他商家办理'));
        }

    }
    /**
     * 添加
     */
    public function add() {
//        $this->checkRule(self::$rule);
        if(!IS_POST) {
            $this->getAddRelation();
            $this->display('add');
        } else {
            $Object = D(CONTROLLER_NAME,'Logic');
            $result = $Object->update(I('post.'));
            if($result) {
                $this->success($Object->getLogicSuccess(), Cookie('__forward__'));
            } else {
                $this->error($Object->getLogicError());
            }
        }
    }


    public function getAddRelation()
    {
        $this->assign('province',$this->getRegionList('','1'));
        $this->assign('Advert',M('MerchantAdvertising')->where(array('type'=>1))->field('money,location,id')->order('location ASC')->select());
        parent::getIndexRelation(); // TODO: Change the autogenerated stub
    }

    public function getRegionList($parent_id = '',$type = '')
    {
        if($parent_id != '')$where['parent_id'] = $parent_id;
        if($type != '')$where['region_type'] = $type;
        return M('region')->where($where)->select();
    }

    public function getRegionAjax($parent_id = '',$type = '')
    {
        if($parent_id != '')$where['parent_id'] = $parent_id;
        if($type != '')$where['region_type'] = $type;
        $this->ajaxReturn(M('region')->where($where)->select());
    }

    public function getAdvertAjax()
    {
        $where['type'] = $_POST['type'];
        $model = M('MerchantAdvertising')->where($where)->field('money,location,id')->order('location ASC')->select();
        $this->ajaxReturn($model);
    }

    /**
     * 下单
     */
    public function addAdPosition()
    {
        $session = session('merInfo');
        sort($_POST['start_time']); // 排序选择的时间
        $data['time'] = implode(',',$_POST['start_time']);  // 时间
        $data['url'] = $_POST['url']; // 链接
        $data['pic'] = $_POST['pic']; // 图片
        $data['order_sn'] = time().rand(11111,99999); // 订单号
        $data['merchant_id'] = $session['mer_id']; // 商家ID
        $data['region'] = $_POST['region']; // 地区
        $data['pay_type'] = $_POST['pay_type']; // 支付方式
        $data['type'] = $_POST['type']; // 轮播位置
        $data['location'] = $_POST['location']; // 位置
        $data['money'] = $_POST['money']; // 价格
        if(empty($data['url']))$this->ajaxReturn(array('status'=>0,'info'=>'请填写链接地址','url'=>''));
        if(empty($data['pic']))$this->ajaxReturn(array('status'=>0,'info'=>'请上传轮播图片','url'=>''));
        if(empty($data['region']))$this->ajaxReturn(array('status'=>0,'info'=>'请选择要投放的地区','url'=>''));
        if($data['money'] == 0)$this->ajaxReturn(array('status'=>0,'info'=>'请选择投放时间','url'=>''));

        if($data['pay_type'] == 4){
            // 余额支付
            $merchant = M('Merchant')->where(array('id'=>$session['mer_id']))->getField('balance'); // 查询余额
            if($data['money'] > $merchant){
                $this->ajaxReturn(array('status'=>0,'info'=>'您的账户余额不足,请更换支付方式','url'=>''));
            }else{
                $data['pay_status'] = 1;
                $add = M('AdPositionTotal')->data($data)->add(); // 添加总订单
                M('Merchant')->where(array('id'=>$session['mer_id']))->setDec('balance',$data['money']); // 商家余额减掉 $data['money']
                $this->addPayLog(array('type' => 2,'object_id'=>$session['mer_id'],'title'=> '轮播图广告办理','content'=> '余额支付',
                    'symbol'=>0,'money'=>$_POST['money'])); // 支付记录
                foreach($_POST['start_time'] as $k => $v){
                    $list[$k]['url'] = $data['url'];
                    $list[$k]['pic'] = $data['pic'];
                    $list[$k]['region'] = $data['region'];
                    $list[$k]['type'] = $data['type'];
                    $list[$k]['location'] = $data['location'];
                    $list[$k]['merchant_id'] = $data['merchant_id'];
                    $list[$k]['a_p_t_id'] = $add;
                    $list[$k]['start_time'] = strtotime($v);
                    $list[$k]['end_time'] = strtotime("+1day",strtotime($v));
                }
                $AddArr = M('AdPosition')->addAll($list);
                if($AddArr){
                    $this->ajaxReturn(array('status'=>1,'info'=>'办理成功','url'=>U('AdPosition/Index')));
                }
            }
        }else{
            // 第三方支付
            $add = M('AdPositionTotal')->data($data)->add();
            if($add){
                $this -> ajaxReturn(array(
                        'status'=>1,
                        'info'=>'即将跳转到支付界面',
                        'data'=>
                            array('order_sn'=>$data['order_sn']),
                        'url'=>''
                    ));
            }else{
                $this -> ajaxReturn(array(
                    'status' => 0,
                    'info'  => '下单失败'
                ));
            }
        }
    }

}
