<?php

namespace Merchant\Controller;

class AttributeController extends BaseController {
    private $session = '' ;

    public function _initialize()
    {
        $this->session = session('merInfo');
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表页
     */
    function index() {
//        $this->checkRule(self::$rule);
        $Object = D(CONTROLLER_NAME,'Logic');
        $request = I('request.');
        $request['is_merchant'] =  $this->session['mer_id'];
        $result = $Object->getList($request);
        if($result) {
            $menu = D('goods_type') -> where(array('id'=>$_GET['id'])) -> getField('cn_type_name');
            $this->assign('page', $result['page']);
            $this->assign('list', $result['list']);
        } else {
            $this->error($Object->getLogicError());
        }
        // 记录当前列表页的cookie
        Cookie('__forward__',$_SERVER['REQUEST_URI']);
        $this->getIndexRelation();
        $this->display('index');
    }
    /**
     * 添加
     */
    function add() {
//        $this->checkRule(self::$rule);
        if(!IS_POST) {
            $this->getAddRelation();
            $this->display('update');
        } else {
            $Object = D(CONTROLLER_NAME,'Logic');
            $result = $Object->update(I('post.'));
            if($result) {
                $this->success($Object->getLogicSuccess(), Cookie('__forward__'));
            } else {
                $this->error($Object->getLogicError());
            }
        }
    }

    /**
     * 修改
     */
    function update() {
//        $this->checkRule(self::$rule);
        if(!IS_POST) {
            if ($_GET['id']) {
                $Object = D(CONTROLLER_NAME,'Logic');
                $row = $Object->findRow(I('get.'));
                if ($row) {
                    $this->getUpdateRelation();
                    $this->assign('row', $row);
                } else {
                    $this->error($Object->getLogicError());
                }
            }
            $this->display('update');
        } else {
            $Object = D(CONTROLLER_NAME,'Logic');
            $result = $Object->update(I('post.'));
            if($result) {
                $this->success($Object->getLogicSuccess(), Cookie('__forward__'));
            } else {
                $this->error($Object->getLogicError());
            }
        }
    }

}