<?php

namespace Merchant\Controller;

/**
 * [云推广]
 * @author zhouwei
 * Class CloudSpreadController
 * @package Merchant\Controller
 */
class CloudSpreadController extends BaseController
{

    public function getAddRelation()
    {
        $this->assign('adver', $this->getAdverList('6'));//查询 云推广的 价格
        $this->assign('article', $this->getArticleList('16'));//查询 文章
        parent::getAddRelation(); // TODO: Change the autogenerated stub
    }

    /**
     * 查找商品
     */
    public function getGoods()
    {
        $session = session('merInfo');
        $post = $_POST['key'];
        $where['merchant_id'] = $session['mer_id'];
        $where['cn_goods_name'] = array('like', "%" . trim($post) . "%");
        $where['status'] = array('neq', 2);
        $where['audit_status'] = array('eq', 1);
        $where['is_shelves'] = array('eq', 1);
        $model = M('Goods')->where($where)->field('id,cn_goods_name')->select();
        $this->ajaxReturn($model);
    }

    /**
     * 去选择支付方式
     */
    public function toSelectPayType()
    {
        $this->assign('money', $_GET['money']);
        $this->assign('goodsId', $_GET['goodsId']);
        $this->assign('degree', $_GET['degree']);
        $this->display();
    }

    /**
     *  新增一条订单
     */
    public function addOrder()
    {
        $session = session('merInfo');
        $data['merchant_id'] = $session['mer_id'];
        $data['order_sn'] = time().rand(11111, 99999); // 订单号
        $data['change_number'] = $data['total_number'] = $_POST['degree']; // 次数
        $data['pay_money'] = $_POST['money']; // 价格
        $data['pay_type'] = $_POST['type']; // 支付方式
        $data['goods_id'] = $_POST['goodsId']; // 商品ID
        $data['update_time'] = $data['create_time'] = time(); // 创建/修改时间
        $data['status'] = 1;
        if($_POST['type'] == 4){
            // 余额支付
            // 判断 商家余额是否足够
            $m = M('Merchant')->where(array('id'=>$session['mer_id']))->getField('balance');
            if($m < $_POST['money']){
                $this ->ajaxReturn(array('info'=>'您的余额不足以支付,请更换支付方式','status'=>0));
            }
            // 余额够
            $data['pay_status'] = 1; // 支付状态
            $model = M('CloudSpread')->data($data)->add();
            if($model) M('merchant')->where(array('id'=>$session['mer_id']))->setDec($_POST['money']);
             if($model){
                $this -> addPayLog(array('type'=>2,'object_id'=>$session['mer_id'],'title'=>'云推广办理','content'=>'余额支付','symbol'=>0,'money'=>$_POST['money']));
                $this ->ajaxReturn(array('info'=>'办理成功','status'=>1,'url'=>U('CloudSpread/index')));
            }else{
                $this ->ajaxReturn(array('info'=>'办理失败','status'=>1,'url'=>U('CloudSpread/index')));
            }
        }else{

        }

       
    }

    /**
     * 频道列表页
     */
    function details() {
        $Object = D(CONTROLLER_NAME,'Logic');
        $result = $Object->getDetail(I('request.'));
        if($result) {
//         	dump($result['list']);
            $this->assign('page', $result['page']);
            $this->assign('list', $result['list']);
        } else {
            $this->error($Object->getLogicError());
        }
        // 记录当前列表页的cookie
        Cookie('__forward__',$_SERVER['REQUEST_URI']);
        $this->getIndexRelation();
        $this->display('details');
    }
}
