<?php
namespace Merchant\Controller;
/**
 * @author zhouwei
 * Class EvaluateController
 * @package Merchant\Controller
 * 订单管理 - 评价列表 - 控制器
 */
class EvaluateController extends BaseController
{
    function getIndexRelation()
    {
        parent::getIndexRelation(); // TODO: Change the autogenerated stub
    }
}