<?php
namespace Merchant\Controller;

/**
 * Class IndexController
 * @package Manager\Controller
 * 首页控制器
 */
class IndexController extends BaseController {

    private $session = '';

    public function _initialize()
    {
        $this->session = session('merInfo');
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index() {
        $merchant_id = $this->session['mer_id'];
        // 昨日营销额
        $row['yesterday_money'] = number_format($this->getModel('order',array('status'=>array('NOTIN','0,6'),'merchant_id'=>$merchant_id,'submit_order_time'=>array(array('gt',strtotime(date('Y-m-d',strtotime('-1 day')))),array('lt',time())) ),'SUM(trade_price)',3),2,'.',',');
        // 昨日成交量
        $row['yesterday_count'] = $this->getModel('order',array('status'=>array('NOTIN','0,6'),'merchant_id'=>$merchant_id,'submit_order_time'=>array(array('gt',strtotime(date('Y-m-d',strtotime('-1 day')))),array('lt',time())) ),'id',4);
        // 订单总销售额
        $row['total_money'] = number_format($this->getModel('order',array('status'=>array('NOTIN','0,6'),'merchant_id'=>$merchant_id),'SUM(trade_price)',3),2,'.',',');
        // 当前上架商品数
        $row['total_count'] = $this->getModel('goods',array('status'=>array('NOTIN','0,9'),'merchant_id'=>$merchant_id),'id',4);

        $time = array_column($this->getModel('order',array('status'=>array('notin','0,6'),'merchant_id'=>$merchant_id),'submit_order_time',1),'submit_order_time');
        $timeReturn = array('max'=>date('Y-m-d H:i:s',max($time)),'min'=>date('Y-m-d',(M('Merchant')->where(array('id'=>$merchant_id))->getField('create_time'))));

        if($_POST['start_time'] == ''){
            $start_time =date('Y-m-d',(M('Merchant')->where(array('id'=>$merchant_id))->getField('create_time')));
            $end_time = date('Y-m-d',time());
        }else{
            $start_time  =  $_POST['start_time'];
            $end_time = $_POST['end_time'];
        }
        $parameterArray = array(
            array('title'=>'销售额','where'=>array('status'=>array('NOTIN','0,6'),'merchant_id'=>$merchant_id),'obj'=>M('Order'),'flag'=>array('Count','SUM(trade_price)')),
        );
        $this->statisticsOrderMap($start_time,$end_time,$parameterArray);
        $this->assign('row',$row);
        $this->assign('time',$timeReturn);
        $this->display('index');
    }


    // 获取 统计图
    public function statisticsOrderMap($start_time='',$end_time='',$parameter=array())
    {
        $abscissa =   D('Statistical','Service')->createX($start_time,$end_time);// 获取横坐标
        $abscissa= $abscissa['x_date'];
        $resultData =   D('Statistical','Service')->getLineOrderData($start_time,$end_time,$parameter);
        $data = D('Statistical','Service')->createLine($resultData); // 获得时间段下的数据
        $this->assign('abscissa', $abscissa);
        $this->assign('data', $data);
    }


    public function getModel($model,$where,$field='',$type='1')
    {
        switch($type){
            case '1' :
                $return = M($model)->where($where) ->field($field)->select();
                break;
            case '2' :
                $return = M($model)->where($where) ->field($field)->find();
                break;
            case '3' :
                $return = M($model)->where($where) ->getField($field);
                break;
            case '4' :
                $return = M($model)->where($where) -> count();
        }
        return $return;
    }
}
