<?php

namespace Merchant\Controller;

/**
 * @author zhouwei
 * Class MemberCardController
 * @package Merchant\Controller
 * 财务管理-银行管理-控制器
 */
class MemberCardController extends BaseController
{
    public function getAddRelation()
    {
        $row['support'] = M('support_bank') -> select();
        $this->assign('row',$row);
        parent::getAddRelation(); // TODO: Change the autogenerated stub
    }
}