<?php

namespace Merchant\Controller;

/**
 * 商家
 * Class MerchantController
 * @package Manager\Controller
 */
class MerchantController extends BaseController {
    /*
     * ["mer_id"] => string(1) "登录ID"
     * ["mer_account"] => string(11) "手机号"
     * ["last_login_time"] => string(10) "最后登录时间"
     * */
    private $session = '';
    public function _initialize()
    {
        $this->session = session('merInfo');
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    function index(){}


    /**
     * 修改
     */
    function update() {
        if(!IS_POST) {
            $data['id'] = $this->session['mer_id'];
            if ($data) {
                $Object = D(CONTROLLER_NAME,'Logic');
                $row = $Object->findRow($data);
                if ($row) {
                    $this->assign('region_province',M('region')->where(array('region_type'=>1))->select());
                    $this->assign('region_city',M('region')->where(array('parent_id'=>$row['province']))->select());
                    $this->assign('region_district',M('region')->where(array('parent_id'=>$row['city']))->select());
                    $this->getUpdateRelation();
                    $this->assign('row', $row);
                } else {
                    $this->error($Object->getLogicError());
                }
            }
            $this->display('update');
        } else {
            $Object = D(CONTROLLER_NAME,'Logic');
            $result = $Object->update(I('post.'));
            if($result) {
                $this->success($Object->getLogicSuccess());
            } else {
                $this->error($Object->getLogicError());
            }
        }
    }

    /**
     * 修改
     */
    function attestation() {
        if(!IS_POST) {
            $data['id'] = $this->session['mer_id'];
            if ($data) {
                $Object = D(CONTROLLER_NAME,'Logic');
                $row = $Object->findRow($data);
                if ($row) {
                    $this->getUpdateRelation();
                    $this->assign('row', $row);
                } else {
                    $this->error($Object->getLogicError());
                }
            }
            $this->display('attestation');
        } else {
            $Object = D(CONTROLLER_NAME,'Logic');
            $result = $Object->update(I('post.'));
            if($result) {
                $this->success($Object->getLogicSuccess());
            } else {
                $this->error($Object->getLogicError());
            }
        }
    }

    /**
     * 地区
     */
    function getRegionList()
    {
        $post = $_POST;
        if($post){
            $where['parent_id'] = $post['parent_id'];
            $where['region_type'] = array('neq',0);
            $list = M('region')->where($where)->select();
            $this->ajaxReturn(array('data'=>$list,'status'=>1,'info'=>'获取成功'));return false;
        }
        $this->ajaxReturn(array('data'=>array(),'status'=>0,'info'=>'失败'));return false;

    }

    /**
     * 修改手机号
     */
    public function alertPhone()
    {
        $this->assign('Phone',M('Merchant')->where(array('id'=>$_GET['id']))->getField('account'));
        $this->display('alertPhone');
    }

    /**
     * 得到验证码
     */
    public function getCode()
    {
        $post = $_POST;
        if(!preg_match(C('MOBILE'),trim($post['account']))) {
            $this->error('请输入正确的手机号');
        }
        /* 手机号 , 发送方式*/
        $data = D('Sms')->sendVerify(trim($post['account']),'merbind');
        if(!empty($data['success'])){
            $this -> ajaxReturn(array('status'=>'1','info'=>$data['success']));
        }else{
            $this -> ajaxReturn(array('status'=>'0','info'=>$data['error']));
        }
    }

    /**
     * 验证验证码
     */
    public function PutCode()
    {
        $account = trim($_POST['account']);
        $code = trim($_POST['code']);
        $model_code = M('sms')->where(array('type'=>'merbind','way'=>$account,'vc'=>$code,'expire_time'=>array('gt',time())))->count();
        if($model_code <= 0) $this->error('验证失败');
        if($model_code > 0)$this->success('成功',U('Merchant/alertingAccount'));
    }

    public function alertingAccount()
    {
        $this -> display();
    }

    /**
     * 得到验证码
     */
    public function getAlertCode()
    {
        $post = $_POST;
        if(!preg_match(C('MOBILE'),trim($post['account']))) {
            $this->error('请输入正确的手机号');
        }
        if(M('merchant')->where(array('id'=>$_POST['account']))->count() > 0){
            $this->error('该手机号已存在');
        }
        /* 手机号 , 发送方式*/
        $data = D('Sms')->sendVerify(trim($post['account']),'merbind');
        if(!empty($data['success'])){
            $this -> ajaxReturn(array('status'=>'1','info'=>$data['success']));
        }else{
            $this -> ajaxReturn(array('status'=>'0','info'=>$data['error']));
        }
    }

    /**
     * 修改
     */
    public function putAccount()
    {
        $account = $_POST['account'];
        $code = $_POST['code'];
        $model_code = M('sms')->where(array('type'=>'merbind','way'=>$account,'vc'=>$code,'expire_time'=>array('gt',time())))->count();
        if($model_code < 0)$this->error('验证失败');
        $merchant_id = $this->session['mer_id'];
        $model = M('merchant')->where(array('id'=>$merchant_id))->data(array('account'=>$account))->save();
        if($model){
            session('[destroy]');
            $this->success('成功',U('Merchant/update'));
        }else{
            $this->error('修改失败请重新尝试');
        }
    }
}
