<?php

namespace Merchant\Controller;

/**
 * @author zhouwei
 * Class OrderController
 * @package Merchant\Controller
 * 订单管理 - 未完成订单列表 - 控制器
 */
class UnfinishedOrderController extends BaseController {

    public function getIndexRelation()
    {
        $deliveryCompany = M('delivery_company')->select();
        $deliveryNum = count($deliveryCompany);
        foreach($deliveryCompany as $k => $v){
            if($k == 0){
                $str = '<select class="delivery" name="delivery">';
                $str .= '<option value="'.$v['delivery_code'].'">'.$v['company_name'].'</option>';
            }else if($k +1 == $deliveryNum){
                $str .= '<option value="'.$v['delivery_code'].'">'.$v['company_name'].'</option>';
                $str .= '</select>';
                $str .= '<input type="text" name="delivery_sn" class="delivery_sn" placeholder="请输入快递单号"/>';
            }else{
                $str .= '<option value="'.$v['delivery_code'].'">'.$v['company_name'].'</option>';
            }
        }
        $this -> assign('str',$str);
        parent::getIndexRelation(); // TODO: Change the autogenerated stub
    }


}
