<?php

namespace Manager\Logic;

/**
 * @author zhouwei
 * Class ActionLogic
 * @package Manager\Logic
 * 分成比例
 */
class DivideLogic extends BaseLogic {

    /**
     * @param array $request
     * @return array
     * 获取行为列表
     */
    function getList($request = array()) {

    }

    /**
     * @param array $request
     * @return mixed
     */
    function findRow($request = array()) {
        if(!empty($request['id'])) {
            $param['where']['id'] = $request['id'];
        } else {
            $this->setLogicError('参数错误！'); return false;
        }
        $row = D('Divide')->findRow($param);

        if(!$row) {
            $this->setLogicError('未查到此记录！'); return false;
        }
        return $row;
    }

    /**
     * 修改
     * @param array $request
     * ["model"] => string(6) "Divide"
     * ["id"] => string(1) "1"
     *
     * ["divide_a"] => string(4) "0.60"
     * ["divide_b"] => string(4) "0.20"
     * ["divide_c"] => string(4) "0.10"
     * ["divide_d"] => string(4) "0.05"
     * ["divide_m"] => string(4) "0.05"
     *
     * ["divide_p"] => string(4) "0.6"
     * @return bool
     */
    function beforeUpdate($request = array())
    {
        $divide = array($request['divide_a'],$request['divide_b'],$request['divide_c'],$request['divide_d'],$request['divide_e'],$request['divide_m']);
        if(array_sum($divide) > 1){
            $this -> setLogicError('分成比例填写总和大于1,请重新填写');return false;
        }if($request['divide_p'] > 1){
            $this -> setLogicError('平台抽成请输入小于/等于1的比例,请重新填写');return false;
        }
        return parent::beforeUpdate($request); // TODO: Change the autogenerated stub
    }
}